### YamlMime:BusinessCentralApplicationObject
fqName: '"ESCA ConfigPackages"'
alId: ID 71177002
baseKind: Page
kind: PageExtension
parent: 'N:Module::Dynavision_Core::Namespace::'
langs:
- al
extends:
  name: '"Config. Packages"'
  isExternal: true
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::ESCA ConfigPackages
uid: O:PageExtension::ESCA_ConfigPackages
name: '"ESCA ConfigPackages"'
