### YamlMime:BusinessCentralApplicationObject
fqName: '"ESCA Related Settings"'
alId: ID 71096618
baseKind: Page
kind: Page
parent: 'N:Module::Dynavision_Core::Namespace::'
langs:
- al
sourceTableType:
  name: '"ESCA Related Setting"'
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: Related Settings
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "71096601"
  promoted: true
- name: UsageCategory
  value: None
  promoted: false
commentId: O:Page::ESCA Related Settings
uid: O:Page::ESCA_Related_Settings
name: '"ESCA Related Settings"'
