### YamlMime:BusinessCentralApplicationObject
fqName: '"ESCA Related Settings"'
alId: ID 71096643
baseKind: Codeunit
kind: Codeunit
parent: 'N:Module::Dynavision_Core::Namespace::'
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
commentId: O:Codeunit::ESCA Related Settings
uid: O:Codeunit::ESCA_Related_Settings
name: '"ESCA Related Settings"'
